name: app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Map library (latest stable)
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  speech_to_text: ^7.3.0

  # Geospatial utilities
  turf: ^0.0.9
  permission_handler: ^12.0.1
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_image_labeling: ^0.14.1
  # HTTP client
  dio: ^5.7.0
  url_launcher: ^6.1.10
  # Toast notifications
  fluttertoast: ^8.2.4
  shared_preferences: ^2.5.3
  geodesy: ^0.4.0
  # Cupertino icons
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  flutter_tts: ^4.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
