name: app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Map library (latest stable)
  flutter_map: ^8.2.1
  latlong2: ^0.9.0

  # Geospatial utilities
  turf: ^0.0.9

  # HTTP client
  dio: ^5.7.0

  # Toast notifications
  fluttertoast: ^8.2.4
  geodesy: ^0.4.0
  # Cupertino icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
